export const hamburger = document.querySelector('.hamburger');
export const mainNavigation = document.querySelector('.main-navigation__wrapper');
export const hamburgerWrapper = document.querySelector('.hamburger-wrapper');
export const body = document.querySelector('body');
export const siteNavigationLinks = document.querySelectorAll('.site-navigation__link');
export const themeSwitch = document.querySelector('.theme-switch');
export const themeSwitchIcon = themeSwitch.querySelector('.theme-switch__icon use');
export const tabButtons = document.querySelectorAll('.projects__tab-button');
export const projects = document.querySelectorAll('.project__item');
